---
driver:
  name: vagrant

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-16.04
  - name: centos-6.9
  - name: centos-7.2
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[clamav::default]
    attributes:
      clamav:
        clamd:
          enabled: true
        freshclam:
          enabled: true
