---
driver:
  name: dokken
  privileged: true
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  root_path: /opt/verifier
  sudo: true

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /lib/systemd/systemd
  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
  - name: ubuntu-16.04-chef-12
    driver:
      image: ubuntu:16.04
      chef_version: 12.21.1
      pid_one_command: /lib/systemd/systemd
  - name: ubuntu-14.04-chef-12
    driver:
      image: ubuntu:14.04
      chef_version: 12.21.1
      pid_one_command: /sbin/init

suites:
  - name: default
    run_list:
      - recipe[clamav_test]
    verifier:
      inspec_tests:
        - test/smoke/base
        - test/smoke/default
  - name: enabled
    run_list:
      - recipe[clamav_test]
    attributes:
      clamav:
        clamd:
          enabled: true
        freshclam:
          enabled: true
    verifier:
      inspec_tests:
        - test/smoke/base
        - test/smoke/enabled
  - name: remove
    run_list:
      - recipe[clamav_test::remove]
    verifier:
      inspec_tests:
        - test/smoke/remove
