---
driver:
  name: vagrant

platforms:
  - name: ubuntu-14.04
  # - name: ubuntu-12.04
  # - name: debian-8.2
  # - name: centos-7.2
  # - name: centos-6.7
  # - name: centos-5.11
  # - name: ubuntu-14.04-chef-11
  #   driver:
  #     box: bento/ubuntu-14.04
  #   provisioner:
  #     require_chef_omnibus: 11.16.4

suites:
  - name: default
    run_list:
      - recipe[clamav_test]
